[package]
org = "isuruuy"
name = "aupatient"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
path = "/path_to/mysql-connector-java-8.0.26.jar"